//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakeAccountInfo
    {
        public int InfoId { get; set; }
        public System.DateTime Date { get; set; }
        public int Sales { get; set; }
        public int OtherRevenues { get; set; }
        public int SalesReturns { get; set; }
        public int GrossProfit { get; set; }
        public int Wages { get; set; }
        public int Depreciation { get; set; }
        public int Rent { get; set; }
        public int OtherSupplies { get; set; }
        public int Utilities { get; set; }
        public int Insurance { get; set; }
        public int Maintenance { get; set; }
        public int Advertising { get; set; }
        public int OtherExpenses { get; set; }
    }
}
