//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int PurchaseItemId { get; set; }
        public System.DateTime InTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public int StorageId { get; set; }
        public int PurchaseId { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
